services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/video_analysis_db
      - QUERY=${QUERY}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - video-analysis-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video_analysis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - video-analysis-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  video-analysis-network:
    driver: bridge

volumes:
  postgres-data:
